# Generated by Django 5.2.4 on 2025-07-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='total_harga',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
