# Generated by Django 5.2.4 on 2025-07-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan',
            name='kasir',
        ),
        migrations.AddField(
            model_name='penjualan',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaksi'),
        ),
    ]
